// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePostInput struct {
	Body   string   `json:"body"`
	Images []string `json:"images"`
}

type FollowUserInput struct {
	Username string `json:"username"`
}

type SignedUploadInput struct {
	FileName    string `json:"fileName"`
	ContentType string `json:"contentType"`
}

type UserCreds struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
