// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/m-butterfield/social/app/data"
)

type CreatePostInput struct {
	Body   string   `json:"body"`
	Images []string `json:"images"`
}

type GetUserInput struct {
	Username string `json:"username"`
}

type SignedUploadInput struct {
	FileName    string `json:"fileName"`
	ContentType string `json:"contentType"`
}

type UserCreds struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserPostResponse struct {
	Posts []*data.Post `json:"posts"`
	User  *data.User   `json:"user"`
}
